### ISSUE TITLE
using in kong ingress controller

### ISSUE THREAD

**Issue by nithinkd-geon** [wshirey/kong-plugin-jwt-claims-headers#7]
hello @wshirey 

when i try to use this in kong ingress controller below exception is occured

jwt-claims-headers map[] false  0a36ec9f-b691-4df1-8aca-9a1a488c1a05 } in service c4aaa532-4254-4dd1-a20a-ba0b7755c19c: json: cannot unmarshal string into Go struct field Plugin.config of type v1.Configuration

the kongplugin  resource config is below

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-jwt-header
  labels:
plugin: "jwt-claims-headers"

is that anything additional to work with kong ingress?

**Comment by wshirey** [comment]
I haven’t tested this with Kong ingress controller and this was originally written against kong 0.10.0. Unfortunately I don’t have any experience with kong ingress controller to be of any assistance.

**Comment by nithinkd-geon** [comment]
no problem..
